from __future__ import annotations

import io
import re
import zipfile

from prism.models import RepositoryChangeStatus, RepositoryMap


def build_obsidian_vault(repository_map: RepositoryMap) -> bytes:
    """Return a small Obsidian-ready vault containing one Markdown note per block."""

    root = _vault_name(repository_map)
    archive_buffer = io.BytesIO()
    with zipfile.ZipFile(archive_buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"{root}/README.md", _index_note(repository_map))
        for block in repository_map.blocks:
            archive.writestr(f"{root}/{block.note_path}", block.note)
    return archive_buffer.getvalue()


def obsidian_vault_filename(repository_map: RepositoryMap) -> str:
    return f"{_vault_name(repository_map)}.zip"


def _index_note(repository_map: RepositoryMap) -> str:
    lines = [
        "---",
        f'repository: "{repository_map.repository}"',
        f'head_sha: "{repository_map.head_sha}"',
        "tags: [prism, repository-map]",
        "---",
        "",
        f"# {repository_map.repository} architecture map",
        "",
    ]
    if repository_map.overview:
        lines.extend([repository_map.overview, ""])
    lines.extend(
        [
            "## Architecture blocks",
            "",
            "PRism highlights blocks with direct pull-request changes and their connected blocks.",
            "",
        ]
    )
    changed_statuses = {
        RepositoryChangeStatus.ADDED,
        RepositoryChangeStatus.MODIFIED,
        RepositoryChangeStatus.REMOVED,
        RepositoryChangeStatus.RENAMED,
    }
    for block in sorted(
        repository_map.blocks,
        key=lambda item: (item.status not in changed_statuses, item.label.lower()),
    ):
        status = f" — **{block.status.value}**" if block.status != RepositoryChangeStatus.UNCHANGED else ""
        note_without_extension = block.note_path.removesuffix(".md")
        lines.append(
            f"- [[{note_without_extension}|{block.label}]]{status} — "
            f"{len(block.files)} file{'s' if len(block.files) != 1 else ''}"
        )
    lines.extend(["", "Generated by PRism.", ""])
    return "\n".join(lines)


def _vault_name(repository_map: RepositoryMap) -> str:
    repository = re.sub(r"[^A-Za-z0-9_.-]+", "-", repository_map.repository).strip("-")
    return f"PRism-{repository}-{repository_map.head_sha[:8]}"
